name: Deploy to FTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 45.132.157.19
        username: u983503200.Grupo2703
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Directorio local que se va a subir (por ejemplo, toda la carpeta del proyecto)
        server-dir: /UdeC_Alimentacion/  # Directorio en el servidor donde se van a subir los archivos (asegúrate de que termine en '/')
